### ISSUE TITLE
Port this to a cross-platform programming language 

### ISSUE THREAD

**Issue by birgersp** [thomasfn/ftl-overdrive#11]
Got really excited when I found this repo, until I saw it will be written in C#. What's the point of open source software if I need to pay hundreds of dollars for a Windows license?

Preferably c++, but since C# was initially selected how about java?

**Comment by KuroSaru** [comment]
C# can be run via mono which is open source, plus Microsoft have made part of core .Net framework for C# open source via github. but this project been dead for a long time sadly.

**Comment by birgersp** [comment]
I'm a little embarrassed, I was under the impression C# applications was a bitch to run in anything other than Windows. 

Would be awesome to see this project realized. FTL is an awesome game but "simple" enough (at least its core features) to be a open source hobby project...

**Comment by kartoFlane** [comment]
This might interest you; on the [FTL forums, there's a project](http://www.ftlgame.com/forum/viewtopic.php?f=12&t=28850) that re-imagines FTL as a multiplayer game. It's actually more successful than the past attempts at rewriting the game, since it actually is playable. It's also written in Java, so you _should_ be able to run it on a non-Windows machine.  
One issue is that the dev keeps the source closed, though, at least for the time being.

**Comment by birgersp** [comment]
Very interesting, thanks a lot!
